[package]
name = "Yujin_WDK"
version = "0.0.1"
edition = "2021"
authors = ["LunaStev"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "Yujin_WDK"
path = "src/main.rs"

[dependencies]
log = "0.4.*"
getopts = "0.2.*"